### ISSUE TITLE
RequestError: Your billing address has missing information or is invalid.

### ISSUE THREAD

**Issue by fresh5447** [bigcommerce/checkout-sdk-js#648]
I am receiving this error when I go to submit payment:

```
theme-bundle.chunk.5.js:87418 PAYMENT ERROR RequestError: Your billing address has missing information or is invalid. Please return to billing section of checkout and provide valid details.
```

I am logging the state of the checkout data as I submit so I can further inspect my billing address. Here is that data:

```
billingAddress:
  address1: "1010 Main St"
  address2: ""
  city: "Whitefish"
  company: ""
  country: "United States"
  countryCode: "US"
  customFields: []
  email: ""
   firstName: "Dirk"
  id: "5d3f781149630"
  lastName: "Dirkowski"
  phone: "4067554545"
  postalCode: "59937"
  stateOrProvince: "Montana"
  stateOrProvinceCode: "MT"
```

Apparently something here is invalid, but I am not seeing it.

![Screen Shot 2019-07-29 at 4 56 36 PM](https://user-images.githubusercontent.com/5817201/62088224-dcd32200-b221-11e9-9804-970b3529a92c.png)
